# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jeffbush/src/NyuziProcessor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jeffbush/src/NyuziProcessor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jeffbush/src/NyuziProcessor/CMakeFiles /Users/jeffbush/src/NyuziProcessor/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jeffbush/src/NyuziProcessor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named emulator

# Build rule for target.
emulator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 emulator
.PHONY : emulator

# fast build rule for target.
emulator/fast:
	$(MAKE) -f tools/emulator/CMakeFiles/emulator.dir/build.make tools/emulator/CMakeFiles/emulator.dir/build
.PHONY : emulator/fast

#=============================================================================
# Target rules for targets named mkfs

# Build rule for target.
mkfs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mkfs
.PHONY : mkfs

# fast build rule for target.
mkfs/fast:
	$(MAKE) -f tools/mkfs/CMakeFiles/mkfs.dir/build.make tools/mkfs/CMakeFiles/mkfs.dir/build
.PHONY : mkfs/fast

#=============================================================================
# Target rules for targets named serial_boot

# Build rule for target.
serial_boot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 serial_boot
.PHONY : serial_boot

# fast build rule for target.
serial_boot/fast:
	$(MAKE) -f tools/serial_boot/CMakeFiles/serial_boot.dir/build.make tools/serial_boot/CMakeFiles/serial_boot.dir/build
.PHONY : serial_boot/fast

#=============================================================================
# Target rules for targets named repak

# Build rule for target.
repak: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 repak
.PHONY : repak

# fast build rule for target.
repak/fast:
	$(MAKE) -f tools/repak/CMakeFiles/repak.dir/build.make tools/repak/CMakeFiles/repak.dir/build
.PHONY : repak/fast

#=============================================================================
# Target rules for targets named c

# Build rule for target.
c : cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 c
.PHONY : c

# fast build rule for target.
c/fast:
	$(MAKE) -f software/libs/libc/CMakeFiles/c.dir/build.make software/libs/libc/CMakeFiles/c.dir/build
.PHONY : c/fast

#=============================================================================
# Target rules for targets named os-kern

# Build rule for target.
os-kern: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 os-kern
.PHONY : os-kern

# fast build rule for target.
os-kern/fast:
	$(MAKE) -f software/libs/libos/kernel/CMakeFiles/os-kern.dir/build.make software/libs/libos/kernel/CMakeFiles/os-kern.dir/build
.PHONY : os-kern/fast

#=============================================================================
# Target rules for targets named os-bare

# Build rule for target.
os-bare: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 os-bare
.PHONY : os-bare

# fast build rule for target.
os-bare/fast:
	$(MAKE) -f software/libs/libos/bare-metal/CMakeFiles/os-bare.dir/build.make software/libs/libos/bare-metal/CMakeFiles/os-bare.dir/build
.PHONY : os-bare/fast

#=============================================================================
# Target rules for targets named render

# Build rule for target.
render: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 render
.PHONY : render

# fast build rule for target.
render/fast:
	$(MAKE) -f software/libs/librender/CMakeFiles/render.dir/build.make software/libs/librender/CMakeFiles/render.dir/build
.PHONY : render/fast

#=============================================================================
# Target rules for targets named console

# Build rule for target.
console: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 console
.PHONY : console

# fast build rule for target.
console/fast:
	$(MAKE) -f software/libs/libconsole/CMakeFiles/console.dir/build.make software/libs/libconsole/CMakeFiles/console.dir/build
.PHONY : console/fast

#=============================================================================
# Target rules for targets named compiler-rt

# Build rule for target.
compiler-rt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 compiler-rt
.PHONY : compiler-rt

# fast build rule for target.
compiler-rt/fast:
	$(MAKE) -f software/libs/compiler-rt/CMakeFiles/compiler-rt.dir/build.make software/libs/compiler-rt/CMakeFiles/compiler-rt.dir/build
.PHONY : compiler-rt/fast

#=============================================================================
# Target rules for targets named plasma

# Build rule for target.
plasma: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 plasma
.PHONY : plasma

# fast build rule for target.
plasma/fast:
	$(MAKE) -f software/apps/plasma/CMakeFiles/plasma.dir/build.make software/apps/plasma/CMakeFiles/plasma.dir/build
.PHONY : plasma/fast

#=============================================================================
# Target rules for targets named consoletest

# Build rule for target.
consoletest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 consoletest
.PHONY : consoletest

# fast build rule for target.
consoletest/fast:
	$(MAKE) -f software/apps/consoletest/CMakeFiles/consoletest.dir/build.make software/apps/consoletest/CMakeFiles/consoletest.dir/build
.PHONY : consoletest/fast

#=============================================================================
# Target rules for targets named hello_world

# Build rule for target.
hello_world: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hello_world
.PHONY : hello_world

# fast build rule for target.
hello_world/fast:
	$(MAKE) -f software/apps/hello_world/CMakeFiles/hello_world.dir/build.make software/apps/hello_world/CMakeFiles/hello_world.dir/build
.PHONY : hello_world/fast

#=============================================================================
# Target rules for targets named sceneview

# Build rule for target.
sceneview: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sceneview
.PHONY : sceneview

# fast build rule for target.
sceneview/fast:
	$(MAKE) -f software/apps/sceneview/CMakeFiles/sceneview.dir/build.make software/apps/sceneview/CMakeFiles/sceneview.dir/build
.PHONY : sceneview/fast

#=============================================================================
# Target rules for targets named mandelbrot

# Build rule for target.
mandelbrot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mandelbrot
.PHONY : mandelbrot

# fast build rule for target.
mandelbrot/fast:
	$(MAKE) -f software/apps/mandelbrot/CMakeFiles/mandelbrot.dir/build.make software/apps/mandelbrot/CMakeFiles/mandelbrot.dir/build
.PHONY : mandelbrot/fast

#=============================================================================
# Target rules for targets named rotozoom

# Build rule for target.
rotozoom: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rotozoom
.PHONY : rotozoom

# fast build rule for target.
rotozoom/fast:
	$(MAKE) -f software/apps/rotozoom/CMakeFiles/rotozoom.dir/build.make software/apps/rotozoom/CMakeFiles/rotozoom.dir/build
.PHONY : rotozoom/fast

#=============================================================================
# Target rules for targets named shadow_map

# Build rule for target.
shadow_map: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shadow_map
.PHONY : shadow_map

# fast build rule for target.
shadow_map/fast:
	$(MAKE) -f software/apps/shadow_map/CMakeFiles/shadow_map.dir/build.make software/apps/shadow_map/CMakeFiles/shadow_map.dir/build
.PHONY : shadow_map/fast

#=============================================================================
# Target rules for targets named doom

# Build rule for target.
doom: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doom
.PHONY : doom

# fast build rule for target.
doom/fast:
	$(MAKE) -f software/apps/doom/CMakeFiles/doom.dir/build.make software/apps/doom/CMakeFiles/doom.dir/build
.PHONY : doom/fast

#=============================================================================
# Target rules for targets named quakeview

# Build rule for target.
quakeview: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 quakeview
.PHONY : quakeview

# fast build rule for target.
quakeview/fast:
	$(MAKE) -f software/apps/quakeview/CMakeFiles/quakeview.dir/build.make software/apps/quakeview/CMakeFiles/quakeview.dir/build
.PHONY : quakeview/fast

#=============================================================================
# Target rules for targets named hash

# Build rule for target.
hash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hash
.PHONY : hash

# fast build rule for target.
hash/fast:
	$(MAKE) -f software/benchmarks/hash/CMakeFiles/hash.dir/build.make software/benchmarks/hash/CMakeFiles/hash.dir/build
.PHONY : hash/fast

#=============================================================================
# Target rules for targets named membench

# Build rule for target.
membench: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 membench
.PHONY : membench

# fast build rule for target.
membench/fast:
	$(MAKE) -f software/benchmarks/membench/CMakeFiles/membench.dir/build.make software/benchmarks/membench/CMakeFiles/membench.dir/build
.PHONY : membench/fast

#=============================================================================
# Target rules for targets named dhrystone

# Build rule for target.
dhrystone: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dhrystone
.PHONY : dhrystone

# fast build rule for target.
dhrystone/fast:
	$(MAKE) -f software/benchmarks/dhrystone/CMakeFiles/dhrystone.dir/build.make software/benchmarks/dhrystone/CMakeFiles/dhrystone.dir/build
.PHONY : dhrystone/fast

#=============================================================================
# Target rules for targets named kernel

# Build rule for target.
kernel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kernel
.PHONY : kernel

# fast build rule for target.
kernel/fast:
	$(MAKE) -f software/kernel/CMakeFiles/kernel.dir/build.make software/kernel/CMakeFiles/kernel.dir/build
.PHONY : kernel/fast

#=============================================================================
# Target rules for targets named bootrom

# Build rule for target.
bootrom: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bootrom
.PHONY : bootrom

# fast build rule for target.
bootrom/fast:
	$(MAKE) -f software/bootrom/CMakeFiles/bootrom.dir/build.make software/bootrom/CMakeFiles/bootrom.dir/build
.PHONY : bootrom/fast

#=============================================================================
# Target rules for targets named srams

# Build rule for target.
srams: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 srams
.PHONY : srams

# fast build rule for target.
srams/fast:
	$(MAKE) -f hardware/CMakeFiles/srams.dir/build.make hardware/CMakeFiles/srams.dir/build
.PHONY : srams/fast

#=============================================================================
# Target rules for targets named fpgalint

# Build rule for target.
fpgalint: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fpgalint
.PHONY : fpgalint

# fast build rule for target.
fpgalint/fast:
	$(MAKE) -f hardware/CMakeFiles/fpgalint.dir/build.make hardware/CMakeFiles/fpgalint.dir/build
.PHONY : fpgalint/fast

#=============================================================================
# Target rules for targets named autos

# Build rule for target.
autos: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 autos
.PHONY : autos

# fast build rule for target.
autos/fast:
	$(MAKE) -f hardware/CMakeFiles/autos.dir/build.make hardware/CMakeFiles/autos.dir/build
.PHONY : autos/fast

#=============================================================================
# Target rules for targets named vcsbuild

# Build rule for target.
vcsbuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vcsbuild
.PHONY : vcsbuild

# fast build rule for target.
vcsbuild/fast:
	$(MAKE) -f hardware/CMakeFiles/vcsbuild.dir/build.make hardware/CMakeFiles/vcsbuild.dir/build
.PHONY : vcsbuild/fast

#=============================================================================
# Target rules for targets named verilator_model

# Build rule for target.
verilator_model: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 verilator_model
.PHONY : verilator_model

# fast build rule for target.
verilator_model/fast:
	$(MAKE) -f hardware/CMakeFiles/verilator_model.dir/build.make hardware/CMakeFiles/verilator_model.dir/build
.PHONY : verilator_model/fast

#=============================================================================
# Target rules for targets named program

# Build rule for target.
program: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 program
.PHONY : program

# fast build rule for target.
program/fast:
	$(MAKE) -f hardware/fpga/de2-115/CMakeFiles/program.dir/build.make hardware/fpga/de2-115/CMakeFiles/program.dir/build
.PHONY : program/fast

#=============================================================================
# Target rules for targets named synthesize

# Build rule for target.
synthesize: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 synthesize
.PHONY : synthesize

# fast build rule for target.
synthesize/fast:
	$(MAKE) -f hardware/fpga/de2-115/CMakeFiles/synthesize.dir/build.make hardware/fpga/de2-115/CMakeFiles/synthesize.dir/build
.PHONY : synthesize/fast

#=============================================================================
# Target rules for targets named blinky

# Build rule for target.
blinky: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blinky
.PHONY : blinky

# fast build rule for target.
blinky/fast:
	$(MAKE) -f tests/fpga/blinky/CMakeFiles/blinky.dir/build.make tests/fpga/blinky/CMakeFiles/blinky.dir/build
.PHONY : blinky/fast

#=============================================================================
# Target rules for targets named chargen

# Build rule for target.
chargen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chargen
.PHONY : chargen

# fast build rule for target.
chargen/fast:
	$(MAKE) -f tests/fpga/uart_chargen/CMakeFiles/chargen.dir/build.make tests/fpga/uart_chargen/CMakeFiles/chargen.dir/build
.PHONY : chargen/fast

#=============================================================================
# Target rules for targets named sdmmc_dump

# Build rule for target.
sdmmc_dump: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sdmmc_dump
.PHONY : sdmmc_dump

# fast build rule for target.
sdmmc_dump/fast:
	$(MAKE) -f tests/fpga/sdmmc_dump/CMakeFiles/sdmmc_dump.dir/build.make tests/fpga/sdmmc_dump/CMakeFiles/sdmmc_dump.dir/build
.PHONY : sdmmc_dump/fast

#=============================================================================
# Target rules for targets named sdmmc_native

# Build rule for target.
sdmmc_native: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sdmmc_native
.PHONY : sdmmc_native

# fast build rule for target.
sdmmc_native/fast:
	$(MAKE) -f tests/fpga/sdmmc_native/CMakeFiles/sdmmc_native.dir/build.make tests/fpga/sdmmc_native/CMakeFiles/sdmmc_native.dir/build
.PHONY : sdmmc_native/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... emulator"
	@echo "... mkfs"
	@echo "... serial_boot"
	@echo "... repak"
	@echo "... c"
	@echo "... os-kern"
	@echo "... os-bare"
	@echo "... render"
	@echo "... console"
	@echo "... compiler-rt"
	@echo "... plasma"
	@echo "... consoletest"
	@echo "... hello_world"
	@echo "... sceneview"
	@echo "... mandelbrot"
	@echo "... rotozoom"
	@echo "... shadow_map"
	@echo "... doom"
	@echo "... quakeview"
	@echo "... hash"
	@echo "... membench"
	@echo "... dhrystone"
	@echo "... kernel"
	@echo "... bootrom"
	@echo "... srams"
	@echo "... fpgalint"
	@echo "... autos"
	@echo "... vcsbuild"
	@echo "... verilator_model"
	@echo "... program"
	@echo "... synthesize"
	@echo "... blinky"
	@echo "... chargen"
	@echo "... sdmmc_dump"
	@echo "... sdmmc_native"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

