# This file auto-generated by ' + sys.argv[0] + '. Do not edit.

			.globl _start
			.align 64
value1:		.long 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16
value2:		.long 0xaaaaaaaa, 0xbbbbbbbb, 0xcccccccc, 0xdddddddd, 0xeeeeeeee, 0xffffffff
			.long 0x11111111, 0x22222222, 0x33333333, 0x44444444, 0x55555555, 0x66666666
			.long 0x77777777, 0x88888888, 0x99999999
mask:		.long 0x5a5a

_start:		load_v v0, value2
			load_v v1, value1
			load_32 s0, mask

		or s1, s2, s3
		and s3, s1, s2
		xor s2, s3, s1
		add_i s1, s2, s3
		sub_i s3, s1, s2
		ashr s2, s3, s1
		shr s1, s2, s3
		shr s3, s1, s2
		or v2, v3, s1
		and v1, v2, s3
		xor v3, v1, s2
		add_i v2, v3, s1
		sub_i v1, v2, s3
		ashr v3, v1, s2
		shr v2, v3, s1
		shr v1, v2, s3
		or_mask v3, s10, v1, s2
		and_mask v2, s10, v3, s1
		xor_mask v1, s10, v2, s3
		add_i_mask v3, s10, v1, s2
		sub_i_mask v2, s10, v3, s1
		ashr_mask v1, s10, v2, s3
		shr_mask v3, s10, v1, s2
		shr_mask v2, s10, v3, s1
		or_invmask v1, s10, v2, s3
		and_invmask v3, s10, v1, s2
		xor_invmask v2, s10, v3, s1
		add_i_invmask v1, s10, v2, s3
		sub_i_invmask v3, s10, v1, s2
		ashr_invmask v2, s10, v3, s1
		shr_invmask v1, s10, v2, s3
		shr_invmask v3, s10, v1, s2
		or v2, v3, v1
		and v1, v2, v3
		xor v3, v1, v2
		add_i v2, v3, v1
		sub_i v1, v2, v3
		ashr v3, v1, v2
		shr v2, v3, v1
		shr v1, v2, v3
		or_mask v3, s10, v1, v2
		and_mask v2, s10, v3, v1
		xor_mask v1, s10, v2, v3
		add_i_mask v3, s10, v1, v2
		sub_i_mask v2, s10, v3, v1
		ashr_mask v1, s10, v2, v3
		shr_mask v3, s10, v1, v2
		shr_mask v2, s10, v3, v1
		or_invmask v1, s10, v2, v3
		and_invmask v3, s10, v1, v2
		xor_invmask v2, s10, v3, v1
		add_i_invmask v1, s10, v2, v3
		sub_i_invmask v3, s10, v1, v2
		ashr_invmask v2, s10, v3, v1
		shr_invmask v1, s10, v2, v3
		shr_invmask v3, s10, v1, v2
		or s2, s3, 479
		and s1, s2, 83
		xor s3, s1, 182
		add_i s2, s3, 293
		sub_i s1, s2, 91
		ashr s3, s1, 342
		shr s2, s3, 161
		shr s1, s2, 426
		or v3, v1, 407
		and v2, v3, 52
		xor v1, v2, 500
		add_i v3, v1, 510
		sub_i v2, v3, 467
		ashr v1, v2, 145
		shr v3, v1, 319
		shr v2, v3, 29
		or_mask v1, s10, v2, 137
		and_mask v3, s10, v1, 153
		xor_mask v2, s10, v3, 226
		add_i_mask v1, s10, v2, 392
		sub_i_mask v3, s10, v1, 60
		ashr_mask v2, s10, v3, 97
		shr_mask v1, s10, v2, 474
		shr_mask v3, s10, v1, 472
		or_invmask v2, s10, v3, 320
		and_invmask v1, s10, v2, 181
		xor_invmask v3, s10, v1, 160
		add_i_invmask v2, s10, v3, 137
		sub_i_invmask v1, s10, v2, 359
		ashr_invmask v3, s10, v1, 459
		shr_invmask v2, s10, v3, 209
		shr_invmask v1, s10, v2, 353
		or v3, s1, 335
		and v2, s3, 202
		xor v1, s2, 337
		add_i v3, s1, 140
		sub_i v2, s3, 59
		ashr v1, s2, 105
		shr v3, s1, 248
		shr v2, s3, 146
		or_mask v1, s10, s2, 219
		and_mask v3, s10, s1, 351
		xor_mask v2, s10, s3, 254
		add_i_mask v1, s10, s2, 476
		sub_i_mask v3, s10, s1, 215
		ashr_mask v2, s10, s3, 4
		shr_mask v1, s10, s2, 353
		shr_mask v3, s10, s1, 101
		or_invmask v2, s10, s3, 244
		and_invmask v1, s10, s2, 346
		xor_invmask v3, s10, s1, 125
		add_i_invmask v2, s10, s3, 149
		sub_i_invmask v1, s10, s2, 28
		ashr_invmask v3, s10, s1, 398
		shr_invmask v2, s10, s3, 149
		shr_invmask v1, s10, s2, 269
		clz s3, s1
		ctz s1, s3
		move s3, s1
		clz v1, v3
		ctz v3, v1
		move v1, v3
		clz_mask v3, s10, v1
		ctz_mask v1, s10, v3
		move_mask v3, s10, v1
		clz_invmask v1, s10, v3
		ctz_invmask v3, s10, v1
		move_invmask v1, s10, v3
		clz v3, v1
		ctz v1, v3
		move v3, v1
		clz_mask v1, s10, v3
		ctz_mask v3, s10, v1
		move_mask v1, s10, v3
		clz_invmask v3, s10, v1
		ctz_invmask v1, s10, v3
		move_invmask v3, s10, v1

		setcr s0, 29
done: 	goto done
