# This file auto-generated by generate_int_arith_format.py. Do not edit.

			.globl _start
			.align 64
value1:		.long 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16
value2:		.long 0xaaaaaaaa, 0xbbbbbbbb, 0xcccccccc, 0xdddddddd, 0xeeeeeeee, 0xffffffff
			.long 0x11111111, 0x22222222, 0x33333333, 0x44444444, 0x55555555, 0x66666666
			.long 0x77777777, 0x88888888, 0x99999999
mask:		.long 0x5a5a

_start:		move v0, 0
			load_v v2, value2
			load_v v3, value1
			move s2, 0x456
			move s3, 0x123
			load_32 s10, mask

		or s1, s2, s3
		and s3, s1, s2
		xor s2, s3, s1
		add_i s1, s2, s3
		sub_i s3, s1, s2
		mul_i s2, s3, s1
		ashr s1, s2, s3
		shr s3, s1, s2
		shl s2, s3, s1
		or v1, v2, s3
		and v3, v1, s2
		xor v2, v3, s1
		add_i v1, v2, s3
		sub_i v3, v1, s2
		mul_i v2, v3, s1
		ashr v1, v2, s3
		shr v3, v1, s2
		shl v2, v3, s1
		or_mask v1, s10, v2, s3
		and_mask v3, s10, v1, s2
		xor_mask v2, s10, v3, s1
		add_i_mask v1, s10, v2, s3
		sub_i_mask v3, s10, v1, s2
		mul_i_mask v2, s10, v3, s1
		ashr_mask v1, s10, v2, s3
		shr_mask v3, s10, v1, s2
		shl_mask v2, s10, v3, s1
		or v1, v2, v3
		and v3, v1, v2
		xor v2, v3, v1
		add_i v1, v2, v3
		sub_i v3, v1, v2
		mul_i v2, v3, v1
		ashr v1, v2, v3
		shr v3, v1, v2
		shl v2, v3, v1
		or_mask v1, s10, v2, v3
		and_mask v3, s10, v1, v2
		xor_mask v2, s10, v3, v1
		add_i_mask v1, s10, v2, v3
		sub_i_mask v3, s10, v1, v2
		mul_i_mask v2, s10, v3, v1
		ashr_mask v1, s10, v2, v3
		shr_mask v3, s10, v1, v2
		shl_mask v2, s10, v3, v1
		or s1, s2, 494
		and s3, s1, 168
		xor s2, s3, 447
		add_i s1, s2, 383
		sub_i s3, s1, 69
		mul_i s2, s3, 178
		ashr s1, s2, 148
		shr s3, s1, 259
		shl s2, s3, 306
		or v1, v2, 368
		and v3, v1, 458
		xor v2, v3, 471
		add_i v1, v2, 110
		sub_i v3, v1, 134
		mul_i v2, v3, 439
		ashr v1, v2, 8
		shr v3, v1, 171
		shl v2, v3, 13
		or_mask v1, s10, v2, 153
		and_mask v3, s10, v1, 255
		xor_mask v2, s10, v3, 194
		add_i_mask v1, s10, v2, 90
		sub_i_mask v3, s10, v1, 204
		mul_i_mask v2, s10, v3, 56
		ashr_mask v1, s10, v2, 494
		shr_mask v3, s10, v1, 119
		shl_mask v2, s10, v3, 280
		or v1, s2, 120
		and v3, s1, 89
		xor v2, s3, 284
		add_i v1, s2, 71
		sub_i v3, s1, 182
		mul_i v2, s3, 192
		ashr v1, s2, 100
		shr v3, s1, 281
		shl v2, s3, 391
		or_mask v1, s10, s2, 268
		and_mask v3, s10, s1, 376
		xor_mask v2, s10, s3, 196
		add_i_mask v1, s10, s2, 439
		sub_i_mask v3, s10, s1, 231
		mul_i_mask v2, s10, s3, 510
		ashr_mask v1, s10, s2, 349
		shr_mask v3, s10, s1, 238
		shl_mask v2, s10, s3, 338
		clz s1, s2
		ctz s2, s1
		move s1, s2
		clz v2, v1
		ctz v1, v2
		move v2, v1
		clz_mask v1, s10, v2
		ctz_mask v2, s10, v1
		move_mask v1, s10, v2
		clz v2, v1
		ctz v1, v2
		move v2, v1
		clz_mask v1, s10, v2
		ctz_mask v2, s10, v1
		move_mask v1, s10, v2

		setcr s0, 29
done: 	goto done
