# This file auto-generated by generate_int_arith_format.py. Do not edit.

			.globl _start
			.align 64
value1:		.long 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16
value2:		.long 0xaaaaaaaa, 0xbbbbbbbb, 0xcccccccc, 0xdddddddd, 0xeeeeeeee, 0xffffffff
			.long 0x11111111, 0x22222222, 0x33333333, 0x44444444, 0x55555555, 0x66666666
			.long 0x77777777, 0x88888888, 0x99999999
mask:		.long 0x5a5a

_start:		move v0, 0
			load_v v2, value2
			load_v v3, value1
			move s2, 0x456
			move s3, 0x123
			load_32 s10, mask

		or s1, s2, s3
		and s3, s1, s2
		xor s2, s3, s1
		add_i s1, s2, s3
		sub_i s3, s1, s2
		ashr s2, s3, s1
		shr s1, s2, s3
		shl s3, s1, s2
		or v2, v3, s1
		and v1, v2, s3
		xor v3, v1, s2
		add_i v2, v3, s1
		sub_i v1, v2, s3
		ashr v3, v1, s2
		shr v2, v3, s1
		shl v1, v2, s3
		or_mask v3, s10, v1, s2
		and_mask v2, s10, v3, s1
		xor_mask v1, s10, v2, s3
		add_i_mask v3, s10, v1, s2
		sub_i_mask v2, s10, v3, s1
		ashr_mask v1, s10, v2, s3
		shr_mask v3, s10, v1, s2
		shl_mask v2, s10, v3, s1
		or_invmask v1, s10, v2, s3
		and_invmask v3, s10, v1, s2
		xor_invmask v2, s10, v3, s1
		add_i_invmask v1, s10, v2, s3
		sub_i_invmask v3, s10, v1, s2
		ashr_invmask v2, s10, v3, s1
		shr_invmask v1, s10, v2, s3
		shl_invmask v3, s10, v1, s2
		or v2, v3, v1
		and v1, v2, v3
		xor v3, v1, v2
		add_i v2, v3, v1
		sub_i v1, v2, v3
		ashr v3, v1, v2
		shr v2, v3, v1
		shl v1, v2, v3
		or_mask v3, s10, v1, v2
		and_mask v2, s10, v3, v1
		xor_mask v1, s10, v2, v3
		add_i_mask v3, s10, v1, v2
		sub_i_mask v2, s10, v3, v1
		ashr_mask v1, s10, v2, v3
		shr_mask v3, s10, v1, v2
		shl_mask v2, s10, v3, v1
		or_invmask v1, s10, v2, v3
		and_invmask v3, s10, v1, v2
		xor_invmask v2, s10, v3, v1
		add_i_invmask v1, s10, v2, v3
		sub_i_invmask v3, s10, v1, v2
		ashr_invmask v2, s10, v3, v1
		shr_invmask v1, s10, v2, v3
		shl_invmask v3, s10, v1, v2
		or s2, s3, 281
		and s1, s2, 428
		xor s3, s1, 464
		add_i s2, s3, 409
		sub_i s1, s2, 261
		ashr s3, s1, 303
		shr s2, s3, 230
		shl s1, s2, 393
		or v3, v1, 243
		and v2, v3, 245
		xor v1, v2, 129
		add_i v3, v1, 71
		sub_i v2, v3, 382
		ashr v1, v2, 250
		shr v3, v1, 29
		shl v2, v3, 58
		or_mask v1, s10, v2, 502
		and_mask v3, s10, v1, 367
		xor_mask v2, s10, v3, 204
		add_i_mask v1, s10, v2, 5
		sub_i_mask v3, s10, v1, 133
		ashr_mask v2, s10, v3, 193
		shr_mask v1, s10, v2, 103
		shl_mask v3, s10, v1, 423
		or_invmask v2, s10, v3, 484
		and_invmask v1, s10, v2, 233
		xor_invmask v3, s10, v1, 339
		add_i_invmask v2, s10, v3, 55
		sub_i_invmask v1, s10, v2, 180
		ashr_invmask v3, s10, v1, 465
		shr_invmask v2, s10, v3, 421
		shl_invmask v1, s10, v2, 336
		or v3, s1, 209
		and v2, s3, 416
		xor v1, s2, 267
		add_i v3, s1, 453
		sub_i v2, s3, 23
		ashr v1, s2, 171
		shr v3, s1, 244
		shl v2, s3, 350
		or_mask v1, s10, s2, 54
		and_mask v3, s10, s1, 72
		xor_mask v2, s10, s3, 386
		add_i_mask v1, s10, s2, 208
		sub_i_mask v3, s10, s1, 111
		ashr_mask v2, s10, s3, 92
		shr_mask v1, s10, s2, 365
		shl_mask v3, s10, s1, 370
		or_invmask v2, s10, s3, 448
		and_invmask v1, s10, s2, 227
		xor_invmask v3, s10, s1, 124
		add_i_invmask v2, s10, s3, 270
		sub_i_invmask v1, s10, s2, 122
		ashr_invmask v3, s10, s1, 39
		shr_invmask v2, s10, s3, 284
		shl_invmask v1, s10, s2, 509
		clz s3, s1
		ctz s1, s3
		move s3, s1
		clz v1, v3
		ctz v3, v1
		move v1, v3
		clz_mask v3, s10, v1
		ctz_mask v1, s10, v3
		move_mask v3, s10, v1
		clz_invmask v1, s10, v3
		ctz_invmask v3, s10, v1
		move_invmask v1, s10, v3
		clz v3, v1
		ctz v1, v3
		move v3, v1
		clz_mask v1, s10, v3
		ctz_mask v3, s10, v1
		move_mask v1, s10, v3
		clz_invmask v3, s10, v1
		ctz_invmask v1, s10, v3
		move_invmask v3, s10, v1

		setcr s0, 29
done: 	goto done
